name: CI + CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  
jobs:
  Build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Compile
       run: echo Hello all
       
  DeployDev:
     name: Deploy to Dev
     if: github.event_name == 'pull_request'
     needs: [Build]
     runs-on: ubuntu-latest
     environment:
       name: development
       
     steps:
       - name: Deploy
         run: echo I am deploying!
         
  DeployStaging:
     name: Deploy to Stage
     if: github.event_name == 'pull_request'
     needs: [Build]
     runs-on: ubuntu-latest
     environment:
       name: stage
       
     steps:
       - name: Deploy
         run: echo I am deploying!
         
  DeployProd:
    name: Deploy to Prod
    if: github.event_name == 'pull_request'
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: production
      
    steps:
      - name: Deploy
        run: echo I am deploying!
