name: Manual CI + CD

on:
  workflow_dispatch:
  
jobs:
  Build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Compile
       id: generate_secret_key_names
       run: |
          prefix=$(echo ${{ github.event.inputs.target_environment }})
          echo "::set-output  name=aws_access_key_id_key::${prefix^^}_AWS_TERRAFORM_ACCESS_KEY_ID"
          echo "::set-output  name=aws_secret_access_key_key::${prefix^^}_AWS_TERRAFORM_SECRET_ACCESS_KEY"
       
  DeployDev:
     name: Deploy to Dev
     needs: [Build]
     runs-on: ubuntu-latest
     environment:
       name: development
       
     steps:
       - name: Deploy
         run: echo I am deploying!
         
  DeployStaging:
     name: Deploy to Stage
     needs: [Build]
     runs-on: ubuntu-latest
     environment:
       name: stage
       
     steps:
       - name: Deploy
         run: echo I am deploying!
         
  DeployProd:
    name: Deploy to Prod
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: production
      
    steps:
      - name: Deploy
        run: echo I am deploying!
