name: Manual CI + CD

on:
  workflow_dispatch:
  
jobs:
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!
      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
          exit: 1
       
  DeployDev:
     name: Deploy to Dev
     needs: [Build]
     runs-on: ubuntu-latest
     environment:
       name: development
       
     steps:
       - name: Deploy
         run: echo I am deploying!
         
  DeployStaging:
     name: Deploy to Stage
     needs: [Build]
     runs-on: ubuntu-latest
     environment:
       name: stage
       
     steps:
       - name: Deploy
         run: echo I am deploying!
         
  DeployProd:
    name: Deploy to Prod
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: production
      
    steps:
      - name: Deploy
        run: echo I am deploying!
