name: Manual CI + CD

on:
  workflow_dispatch:
  
env:
  dev: development
  stage: stage
  production: production
  
jobs:
  Build:
   runs-on: ubuntu-latest
   steps:
     - uses: actions/checkout@v3
     - name: Compile
       run: echo Hello all
       
  DeployDev:
     name: Deploy to Dev
     needs: [Build]
     runs-on: ubuntu-latest
     environment:
       name: ${{ env.development }}
       
     steps:
       - name: Deploy
         run: echo I am deploying!
         
  DeployStaging:
     name: Deploy to Stage
     needs: [Build]
     runs-on: ubuntu-latest
     environment:
       name: ${{ env.stage }}
       
     steps:
       - name: Deploy
         run: echo I am deploying!
         
  DeployProd:
    name: Deploy to Prod
    needs: [Build]
    runs-on: ubuntu-latest
    environment:
      name: ${{ env.production }}
      
    steps:
      - name: Deploy
        run: echo I am deploying!
